name: Build Converter EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 # Обновили до v4 для надежности
    - uses: actions/setup-python@v5 # Обновили до v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build EXE
      run: pyinstaller --noconsole --onefile app.py
    - name: Upload EXE
      uses: actions/upload-artifact@v4 # ТУТ БЫЛА ОШИБКА, теперь v4
      with:
        name: MyConverter
        path: dist/app.exe
